Run dotnet core buildpack test with published app versions for different stacks
cloudfoundry/cf-acceptance-tests pull request #601
Opened 2022-09-15 19:27 UTC by mariash

### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

Yes

### What is this change about?

dotnet core buildpack will reach NuGet registry for unpublished apps to get dotnet core library. That makes this test fail in internetless environment. Switch to using published app (e.g. vendor everything). Published apps need to be compiled for the runtime they will be running on, so there are 2 published versions included for cflinuxfs3 and cflinuxfs4. 

Makefile is provided to help rebuild those versions in case of code changes.

### Please provide contextual information.

Slack thread https://vmware.slack.com/archives/CUR2H2KFE/p1663189449408889

### What version of cf-deployment have you run this cf-acceptance-test change against?

e8130a2c616c4c27e215030e571dc441409f9f5b

### Please check all that apply for this PR:

- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [X] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?

- [ ] YES
- [X] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

_CATs should validate common operator workflows._
_CATs is not a regression test suite._
_CATs is run by every component team to validate their releases before promotion._

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

It actually makes it faster because it skips compilation and fetching dependencies during staging.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

2022-09-19 17:58 UTC, ctlong requested changes
In general, I'm a little wary of the dynamic generation approach you've taken, as it's different to the static approach generally taken in CATs, but if it works I'm open to it :).

The change to the dotnet-core app looks good to me. I just have a few comments for the detect suite changes that need to be addressed.

2022-09-19 17:58 UTC, ctlong commented on detect/buildpacks.go
> +				Expect(cf.Cf("push", appName, "-m", DEFAULT_MEMORY_LIMIT, "-p", assetPath).Wait(Config.DetectTimeoutDuration())).To(Exit(0))
I think it makes sense to add a `-s` flag to specify the specific stack to use, right?

2022-09-19 17:58 UTC, ctlong commented on detect/buildpacks.go
> +			It(fmt.Sprintf("[%s] makes the app reachable via its bound route", stack), func() {
`stack` needs to be assigned to a local copy inside of the for loop or else "the It closure will capture the mutating loop variable and all the specs will run against the last element in the loop." (re: [Dynamically Generating Specs](https://onsi.github.io/ginkgo/#dynamically-generating-specs))

2022-09-19 17:58 UTC, ctlong commented on detect/buildpacks.go
> +			It(fmt.Sprintf("[%s] makes the app reachable via its bound route", stack), func() {
Can you please either put `stack` in a Context title or rephrase the It title to something more like `makes the app reachable via its bound route in <stack>`.

2022-09-19 17:58 UTC, ctlong commented on detect/buildpacks.go
> +				if !ok {
Please change this to an expectation, i.e. `Expect(ok).To(BeTrue())`. You can still add your current failure message to that [as an annotation](https://onsi.github.io/gomega/#annotating-assertions).

2022-09-30 19:09 UTC, mariash commented
I think in general cats should provide a way to test against different stacks. The configuration for CATs allows to set a list of stacks to test against, but in reality we only test against one. But this would be a bigger change and would affect many tests. As of now I only changed the dotnet test because we have different pre-compiled assets for dotnet app based on a stack.

2022-09-30 19:35 UTC, mariash commented
@ctlong it looks like I can no longer push to the branch, I opened a new PR from my fork. https://github.com/cloudfoundry/cf-acceptance-tests/pull/610

2022-09-30 19:35 UTC, closed without merging