Run dotnet core buildpack test with published app versions for different stacks
cloudfoundry/cf-acceptance-tests pull request #610
Opened 2022-09-30 19:34 UTC by mariash

### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

Yes

### What is this change about?

dotnet core buildpack will reach NuGet registry for unpublished apps to get dotnet core library. That makes this test fail in internetless environment. Switch to using published app (e.g. vendor everything). Published apps need to be compiled for the runtime they will be running on, so there are 2 published versions included for cflinuxfs3 and cflinuxfs4. 

Makefile is provided to help rebuild those versions in case of code changes.

### Please provide contextual information.

Slack thread https://vmware.slack.com/archives/CUR2H2KFE/p1663189449408889

### What version of cf-deployment have you run this cf-acceptance-test change against?

e8130a2c616c4c27e215030e571dc441409f9f5b

### Please check all that apply for this PR:

- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [X] changes an existing test
- [ ] requires an update to a CATs integration-config

### Did you update the README as appropriate for this change?

- [ ] YES
- [X] N/A

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

It actually makes it faster because it skips compilation and fetching dependencies during staging.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [X] **Slightly Less than Urgent**

2022-09-30 21:44 UTC, ctlong requested changes

2022-09-30 21:44 UTC, ctlong commented on detect/buildpacks.go
> +		for _, stack := range Config.GetStacks() {
`stack` needs to be assigned to a local copy inside of the for loop or else "the It closure will capture the mutating loop variable and all the specs will run against the last element in the loop." (re: [Dynamically Generating Specs](https://onsi.github.io/ginkgo/#dynamically-generating-specs))

2022-09-30 21:54 UTC, ctlong approved these changes

2022-09-30 21:55 UTC, merged

2022-10-12 09:36 UTC, jochenehret commented
We've just noticed that this PR introduces a large amount of resource files to the `assets/dotnet-core/cflinuxfs3` test. This can cause problems when pushing the application. In one of our test environments, we run into a HTTP 504 gateway timeout for the `POST /v3/resource_matches` request. I had to increase the AWS load balancer idle timeout to make the test pass. Here's a link to the failed test: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/experimental-cats/builds/41

Are you aware of this problem? Can you reduce the application's resources?