Add support for positive + negative dynamic ASG tests
cloudfoundry/cf-acceptance-tests pull request #747
Opened 2023-02-22 21:36 UTC by geofffranks

### Are you submitting this PR against the [develop branch](https://github.com/cloudfoundry/cf-acceptance-tests/tree/develop)?

Yes

### What is this change about?

Enables negative testing of dynamic asgs (ensuring that when disabled dynamic updates are not applied)

### Please provide contextual information.

Based on the tests in 

### What version of cf-deployment have you run this cf-acceptance-test change against?

Latest toolsmiths cf-deployment

### Please check all that apply for this PR:

- [ ] introduces a new test --- Are you sure everyone should be running this test?
- [x] changes an existing test
- [x] requires an update to a CATs integration-config

Not sure if this requires an update to integration-config. If CATS is run against an environment with dynamic asgs disabled, and the security group testing enabled, you must also specify `dynamic_asgs_enabled: false` in your test config. When dynamic asgs is enabled (on by default), no changes are needed.

### Did you update the README as appropriate for this change?

- [x] YES
- [ ] N/A

### If you are introducing a new acceptance test, what is your rationale for including it CATs rather than your own acceptance test suite?

No new tests

### How many more (or fewer) seconds of runtime will this change introduce to CATs?

Should not change the runtime for CATS under default circumstances. When dynamic asgs is enable, the test does not change. When disabled, it takes the same time as when enabled.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

2023-02-23 19:48 UTC, ctlong commented
@geofffranks is there any way to dynamically ascertain whether or not dynamic ASGs are turned on?

2023-02-23 20:24 UTC, geofffranks commented
I don't think there's a way that CATS would have access to:

- parse the bosh manifest
- ssh onto a VM and look at configs/processes
- connect to locket and look for the presence of a lock

2023-02-23 21:35 UTC, ctlong requested changes

2023-02-23 21:35 UTC, ctlong commented on security_groups/dynamic_asgs.go
> +	"io/ioutil"
Can you please replace `ioutil` with the corresponding `io` or `os` functions. `ioutil` has been deprecated since go1.16.

2023-02-23 21:35 UTC, ctlong commented on security_groups/dynamic_asgs.go
> +	"github.com/onsi/gomega/gexec"
`gexec` is already dot-imported in this file.

2023-02-24 14:56 UTC, geofffranks commented
@ctlong Thanks for catching those. I've pushed an update

2023-02-24 17:43 UTC, ctlong approved these changes

2023-02-24 17:44 UTC, merged